version: '3'

services:
  mongodb:
    image: mongo:4.4.18
    restart: always
    container_name: DB-Bot-Scrap
    volumes:
      - mongo-data:/data/db
    ports: 
      - 27017:27017      
    environment:
      MONGO_INITDB_ROOT_USERNAME: shadow_zt_hash
      MONGO_INITDB_ROOT_PASSWORD: Yj12@332ZGNJP

  mongo-express:
    image: mongo-express
    restart: always
    container_name: view-mongo
    ports:s
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=shadow_zt_hash
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Yj12@332ZGNJP
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local