services:

  mongo:
    image: mongo
    restart: always
    container_name: db-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 3030

  mongo-express:
    image: mongo-express
    restart: always
    container_name: view-mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 3030
      ME_CONFIG_MONGODB_URL: mongodb://root:3030@mongo:27017/